version: '3'

services:
  prefect-server:
    image: dijarvrella444/prefect-base:latest
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_NODE_TYPE=server
    ports:
      - "4200-4201:4200-4201"
    command: prefect server start
  prefect-worker:
    image: dijarvrella444/prefect-base:latest
    network_mode: "host"
    environment:
      - PREFECT_API_URL=http://10.3.0.4:4200/api
      - PREFECT_NODE_TYPE=worker
    command: prefect worker start --pool "seedoo-custom-worker"