version: '3'

services:
  prefect-server:
    image: seedooinsights/prefect-base:latest
    environment:
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_NODE_TYPE=server
      - BASE_JOB_TEMPLATE_PATH
      - WORK_POOL_NAME
      - WORK_POOL_TYPE
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - MKL_NUM_THREADS
      - NUMBA_NUM_THREADS
      - NUMBA_THREADING_LAYER
      - OMP_NUM_THREADS
      - OPENBLAS_NUM_THREADS
      - SEEDOO_DB_IP
      - SEEDOO_DB_PORT
      - SEEDOO_PRINT_SQL_DEBUG
    ports:
      - "4200-4201:4200-4201"
    command: prefect server start
  prefect-worker:
    image: seedooinsights/prefect-base:latest
    network_mode: "host"
    environment:
      - PREFECT_API_URL=http://10.3.0.4:4200/api
      - PREFECT_NODE_TYPE=worker
    command: prefect worker start --pool "seedoo-custom-worker" --type "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prefect-dev-server:
    image: seedooinsights/prefect-base:latest
    environment:
      - PREFECT_API_URL
      - PREFECT_SERVER_API_HOST
      - PREFECT_NODE_TYPE
      - BASE_JOB_TEMPLATE_PATH
      - WORK_POOL_NAME
      - WORK_POOL_TYPE
      - DOCKER_USERNAME
      - DOCKER_PASSWORD
      - MKL_NUM_THREADS
      - NUMBA_NUM_THREADS
      - NUMBA_THREADING_LAYER
      - OMP_NUM_THREADS
      - OPENBLAS_NUM_THREADS
      - SEEDOO_DB_IP
      - SEEDOO_DB_PORT
      - SEEDOO_PRINT_SQL_DEBUG
      #- PREFECT_DEBUG_MODE=1
    network_mode: "host"
    command: >
      /bin/sh -c "./bootstrap.sh"
    volumes:
      - $PWD/worker-dev-base-job-template.yaml:/opt/prefect/worker-dev-base-job-template.yaml
      - $PWD/bootstrap.sh:/opt/prefect/bootstrap.sh
  prefect-dev-worker:
    image: seedooinsights/prefect-worker:latest
    network_mode: "host"
    environment:
      - PREFECT_API_URL=http://10.3.0.4:4200/api
      - PREFECT_NODE_TYPE=worker
      #- PREFECT_DEBUG_MODE=1
    command: prefect worker start --pool "seedoo-custom-worker" --type "docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock